# Generated by Django 2.2.12 on 2020-07-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20200723_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='ads')),
                ('caption', models.TextField(blank=True, null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
