# Generated by Django 2.2.12 on 2020-07-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('author', models.TextField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type_of_media', models.CharField(choices=[('book', 'Book'), ('podcast', 'Podcast'), ('music', 'Music'), ('photo', 'Photo')], default='book', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'inactive')], default='inactive', max_length=10)),
            ],
        ),
    ]
