# Generated by Django 2.2.12 on 2020-07-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_chat_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='file_name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='media',
            name='file_id',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
