# Generated by Django 2.2.12 on 2020-07-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20200723_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
